name: stitch3d
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7.10
  - pytorch=1.8.1
  - scanpy=1.7.2
  - anndata=0.7.6
  - numpy=1.19.2
  - louvain=0.7.0
  - leidenalg=0.7.0
  - pandas=1.1.5
  - umap-learn=0.4.6
  - numba=0.49.1
  - pot=0.8.1.0
  - h5py=3.1.0